main: fr.flavio0834.invites.Main
name: Invites
version: 0.1
commands:
  invitedby:
    description: Allows you to tell who invited you on the server. Can be used ONE TIME.
    usage: /invitedby <player>
    permission: invites.invitedby
  invited:
    description: Allows you to see who said you invited them on the server.
    usage: /invited
    permission: invites.invited
  invitereward:
    description: Allows you to set the group that will be given to players that invites at least x players on the server, as a reward. Admin command.
    usage: /invitereward <number> <group_name>
    permission: invites.invitereward
  inviterewards:
    description: Allows you to know all the groups that are given as a reward for inviting x players on the server. Admin command.
    usage: /inviterewards
    permission: invites.inviterewards
permissions:
  invites.invited.other:
    description: Allows you to see who said a player invited them on the server.
    default: op